//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALightmapper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>E:\Program Files (x86)\Steam\steamapps\common\dragon age origins\packages\core\override</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection filePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["filePaths"]));
            }
            set {
                this["filePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>E:\Program Files (x86)\Steam\steamapps\common\dragon age origins\packages\core\data\modelmeshdata.erf</string>
  <string>E:\Program Files (x86)\Steam\steamapps\common\dragon age origins\packages\core\data\modelhierarchies.erf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection erfFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["erfFiles"]));
            }
            set {
                this["erfFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int numPhotons {
            get {
                return ((int)(this["numPhotons"]));
            }
            set {
                this["numPhotons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool trueAttenuation {
            get {
                return ((bool)(this["trueAttenuation"]));
            }
            set {
                this["trueAttenuation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int verbosity {
            get {
                return ((int)(this["verbosity"]));
            }
            set {
                this["verbosity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool clearTempFiles {
            get {
                return ((bool)(this["clearTempFiles"]));
            }
            set {
                this["clearTempFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ben\\Documents\\BioWare\\Dragon Age\\temp")]
        public string workingDirectory {
            get {
                return ((string)(this["workingDirectory"]));
            }
            set {
                this["workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ben\\Documents\\BioWare\\Dragon Age\\temp")]
        public string tempDirectory {
            get {
                return ((string)(this["tempDirectory"]));
            }
            set {
                this["tempDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int maxThreads {
            get {
                return ((int)(this["maxThreads"]));
            }
            set {
                this["maxThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double gatherRadius {
            get {
                return ((double)(this["gatherRadius"]));
            }
            set {
                this["gatherRadius"] = value;
            }
        }
    }
}
